### ISSUE TITLE
Couldn't find CVar named 'CombatLogRangeParty'

### ISSUE THREAD

**Issue by GrumbleTime** [Geigerkind/DPSMate#156] opened 2017-10-24 21:45 UTC
In-game error text:
Error: Interface\AddOns\DPSMate\DPSMate_DataBuilder.lua:656: Couldn't find CVar named 'CombatLogRangeParty'

Event occurs at every 'first' login (from username&password to in-game), but not after a logout to selection screen to login. (hope that makes sense)

Began occurring when I updated DPSmate to the current version. I have deleted the lua files as well, but it hasn't changed anything. As a last ditch effort, I ran only DPSmate and KLHthreatmeter on a fresh/clean application of wow, but the lua error message still persists.

**Comment by Road-block** [comment] 2017-10-25 21:16
Duplicate of #150 and #154

**Comment by Geigerkind** [comment] 2017-10-31 11:45
Fixed

**Closed by Geigerkind** 2017-10-31 11:45 UTC
