### ISSUE TITLE
Wrong Class Shows Up

### ISSUE THREAD

**Issue by kmac528** [Geigerkind/DPSMate#160] opened 2017-11-17 21:05 UTC
I show up on DPSMate as a warrior when I'm a rogue. I first tried the addon out on a warrior, but ever since then any class I play shows up as warrior. I've deleted the old dpsmate saved variables on all characters as well.

**Comment by Bezuuuu** [comment] 2017-11-23 15:55
I'm currently having the same problem, I'm playing a Warlock but it shows up as Warrior with both color and icon. Tried the same things to fix it but hasn't worked for me either.

Haven't come across a known workaround that works either.

**Comment by KevinTyrrell** [comment] 2017-11-24 12:53
Same here.

**Comment by elenmerbau** [comment] 2017-12-08 10:44
I have this issue as well.

**Comment by theofficialgimp** [comment] 2018-01-12 02:48
I found a case-by-case fix for this.

1) Close Wow if it's open.
2) Go to your WoW directory and navigate to WTF/Account/ACCOUNTNAME/Server/ CharacterName/SavedVariables
3) Open up DPSMate.lua in a text editor and use Ctrl+f to find your character's name. It should say something like the following:

["MyCharacterName"] = {
		[1] = 1,
		[5] = "Thogkath",
		[8] = 0,
},

Note: the numbers and values may differ

4) After where it says "[1] = 1," on a new line add [2] = "myclass", (don't forget the comma) if [2] is already there but the class is wrong, just change the class.

mine looks like this: 

["Zubbzz"] = {
		[1] = 1,
		[2] = "warlock",
		[5] = "Thogkath",
		[8] = 0,
},

5) Save and repeat steps 2-4 for all characters with this issue

**Comment by KevinTyrrell** [comment] 2018-01-12 08:44
While changing the saved variables file might fix this, I have a feeling the issue is in this function: https://github.com/Geigerkind/DPSMate/blob/master/DPSMate/DPSMate.lua#L564


You can see that it attempts `class and DPSMateUser[class]` and if that evaluates to `false` it will set the class to be a warrior. The same can happen if `classcolor[class]==nil`. One of those two conditions seems to be the case here.

**Comment by Geigerkind** [comment] 2018-01-27 23:09
Made a change, should work better now

**Closed by Geigerkind** 2018-01-27 23:09 UTC
